PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
#model metadata
PREFIX metago: <http://model.geneontology.org/>
PREFIX lego: <http://geneontology.org/lego/> 
#model data
PREFIX part_of: <http://purl.obolibrary.org/obo/BFO_0000050>
PREFIX occurs_in: <http://purl.obolibrary.org/obo/BFO_0000066>
PREFIX enabled_by: <http://purl.obolibrary.org/obo/RO_0002333>
PREFIX has_input: <http://purl.obolibrary.org/obo/RO_0002233>
PREFIX has_output: <http://purl.obolibrary.org/obo/RO_0002234>
PREFIX causally_upstream_of: <http://purl.obolibrary.org/obo/RO_0002411>
PREFIX provides_direct_input_for: <http://purl.obolibrary.org/obo/RO_0002413>
PREFIX directly_positively_regulates: <http://purl.obolibrary.org/obo/RO_0002629>

SELECT  ?cam ?id ?date ?title ?state ?gp_ind (GROUP_CONCAT(?contributor;separator=";") AS ?contributors)  
WHERE {
  GRAPH ?cam {  
        ?cam <http://purl.org/dc/elements/1.1/title> ?title ;
           <http://purl.org/dc/elements/1.1/date> ?date ;
           <http://purl.org/dc/elements/1.1/contributor> ?contributor ;    
           	lego:modelstate ?state . 
	  BIND(IF(bound(?id), ?id, concat("gomodel:", substr(str(?cam), 31))) as ?id) .    
      ?gp_ind rdf:type ?gp_class .
      VALUES(?gp_class <gene_product_class_uris>)
      #e.g. VALUES ?gp_class { <http://identifiers.org/mgi/MGI:87986> <http://identifiers.org/mgi/MGI:1328355> <http://identifiers.org/wormbase/WBGene00002246> }
    }
  } 
  GROUP BY ?id ?date ?title ?cam ?state ?gp_ind 
  ORDER BY desc(?date) desc(?gp_class) 

 